name: 'Sigma'

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          modules: 'qtwebsockets'
          arch: ${{ matrix.os == 'windows-latest' && 'win64_msvc2022_64' || '' }}
          cache: true

      # Just for example
      # - name: Installing dependencies (Linux)
      #   if: matrix.os == 'ubuntu-latest'
      #   run:
      #     sudo apt-get update -y;
      #     sudo apt-get install -y libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype6-dev libboost-all-dev

      # It's commented because we don't have CMakeLists.txt
      - name: Configure Cmake (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cmake -B build -S . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Setup MSVC environment
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure Cmake (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      # Only building, no packaging
      - name: Build project and package
        run: cmake --build build --config Release
          
      # - name: Upload Release Asset
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     ext: ${{
      #       matrix.os == 'ubuntu-latest' && '.tar.gz' ||
      #       matrix.os == 'windows-latest' && '.zip'}}
      #   shell: bash
      #   run: |
      #     TAG=$(git describe --abbrev=0 --tags)
      #     if gh release view "${TAG}" > /dev/null 2>&1; 
      #     then gh release upload "${TAG}" bin/labyrinth${ext};
      #     else gh release create "${TAG}" bin/labyrinth${ext};
      #     fi